"""Generate a SYNTHETIC placeholder segmentation dataset in YOLO-seg format, standing in
for the real Severstal dataset (blocked from download in this build environment for the
same reason as ml/preprocessing/synthetic.py — see docs/segmentation.md).

Not real steel imagery. Exists only to smoke-test the segmentation training/inference
code path end-to-end. Never report metrics from this as real segmentation performance.

Usage:
    python -m ml.segmentation.synthetic_seg --out data_seg --per-class 15
"""
import argparse
import random
import sys
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
from ml.segmentation.configs.classes import CLASS_NAMES
from ml.segmentation.mask_utils import mask_to_yolo_polygons

# Smaller than Severstal's real 256x1600 so a CPU smoke-test run stays fast; the aspect
# ratio (wide strip) is kept representative.
IMG_H, IMG_W = 96, 400


def steel_background(rng: random.Random) -> Image.Image:
    base = 120 + rng.randint(-15, 15)
    grain = np.array(
        [[max(0, min(255, base + rng.gauss(0, 6))) for _ in range(IMG_W)] for _ in range(IMG_H)],
        dtype=np.uint8,
    )
    return Image.fromarray(grain, mode="L").convert("RGB")


def draw_defect_region(draw: ImageDraw.ImageDraw, mask_draw: ImageDraw.ImageDraw, cls_idx: int, rng: random.Random):
    cx, cy = rng.randint(30, IMG_W - 30), rng.randint(15, IMG_H - 15)
    color = rng.randint(20, 70)

    if cls_idx % 4 == 0:
        w, h = rng.randint(30, 60), rng.randint(8, 20)
        box = [cx - w / 2, cy - h / 2, cx + w / 2, cy + h / 2]
        draw.rectangle(box, fill=color)
        mask_draw.rectangle(box, fill=255)
    elif cls_idx % 4 == 1:
        r = rng.randint(6, 14)
        box = [cx - r, cy - r, cx + r, cy + r]
        draw.ellipse(box, fill=color)
        mask_draw.ellipse(box, fill=255)
    elif cls_idx % 4 == 2:
        pts = [(cx + rng.randint(-25, 25), cy + rng.randint(-10, 10)) for _ in range(4)]
        draw.polygon(pts, fill=color)
        mask_draw.polygon(pts, fill=255)
    else:
        length = rng.randint(40, 90)
        x0, y0, x1, y1 = cx - length / 2, cy, cx + length / 2, cy
        draw.line([(x0, y0), (x1, y1)], fill=color, width=6)
        mask_draw.line([(x0, y0), (x1, y1)], fill=255, width=6)


def make_sample(cls_idx: int, rng: random.Random):
    img = steel_background(rng)
    draw = ImageDraw.Draw(img)
    mask_img = Image.new("L", (IMG_W, IMG_H), 0)
    mask_draw = ImageDraw.Draw(mask_img)

    for _ in range(rng.choice([1, 1, 2])):
        draw_defect_region(draw, mask_draw, cls_idx, rng)

    return img, np.array(mask_img)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", default="data_seg")
    parser.add_argument("--per-class", type=int, default=15)
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    rng = random.Random(args.seed)
    out = Path(args.out)
    split_counts = {"train": args.per_class, "val": max(3, args.per_class // 5), "test": max(3, args.per_class // 5)}

    for split, count in split_counts.items():
        img_dir = out / split / "images"
        lbl_dir = out / split / "labels"
        img_dir.mkdir(parents=True, exist_ok=True)
        lbl_dir.mkdir(parents=True, exist_ok=True)
        for cls_idx, cls in enumerate(CLASS_NAMES):
            for i in range(count):
                img, mask = make_sample(cls_idx, rng)
                name = f"{cls}_{split}_{i:04d}"
                img.save(img_dir / f"{name}.jpg", quality=90)
                polygons = mask_to_yolo_polygons(mask)
                lines = [f"{cls_idx} " + " ".join(f"{v:.6f}" for v in poly) for poly in polygons]
                (lbl_dir / f"{name}.txt").write_text("\n".join(lines))
        print(f"{split}: {count * len(CLASS_NAMES)} synthetic images")

    notice = out / "SYNTHETIC_DATA_NOTICE.md"
    notice.write_text(
        "# Synthetic placeholder segmentation data\n\n"
        "Generated by ml/segmentation/synthetic_seg.py. Not real Severstal imagery. "
        "See docs/segmentation.md before treating any metric trained on this as real.\n"
    )
    print(f"Done. Synthetic YOLO-seg dataset written under {out}/")


if __name__ == "__main__":
    main()
